version: "3"
services:
  app:
    build:
      context: .
      dockerfile: resources/docker/Dockerfile.app
    expose:
      - 8080
    ports:
      - "8080:8080"
  web:
    build:
      context: .
      dockerfile: resources/docker/Dockerfile.web
    links:
      - "app:app"
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./view/build:/usr/share/nginx/html
      - ./resources/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    command: ["/bin/bash", "-c", "nginx -g \"daemon off;\""]