version: "3"
services:
  db: 
    image: postgres:13.1
    environment: 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./resources/sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./resources/sql/test-data.sql:/docker-entrypoint-initdb.d/02-test-data.sql
  app:
    build:
      context: .
      dockerfile: resources/docker/Dockerfile.app
    links:
      - "db:db"
    expose:
      - 8080
    ports:
      - "8080:8080"
  web:
    build:
      context: .
      dockerfile: resources/docker/Dockerfile.web
    links:
      - "app:app"
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./view/build:/usr/share/nginx/html
      - ./resources/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    command: ["/bin/bash", "-c", "nginx -g \"daemon off;\""]