FROM nginx:1.19.6

ENV HTTPS_METHOD=noredirect

RUN chgrp nginx /var/cache/nginx/
RUN chmod -R g+w /var/cache/nginx/
RUN sed --regexp-extended --in-place=.bak 's%^pid\s+/var/run/nginx.pid;%pid /var/tmp/nginx.pid;%' /etc/nginx/nginx.conf

COPY view/build/  /usr/share/nginx/html

RUN chgrp nginx  /usr/share/nginx/html
RUN chmod -R g+w  /usr/share/nginx/html

COPY ./resources/nginx/nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html

CMD ["/bin/bash", "-c", "nginx -g \"daemon off;\""]