CREATE TABLE IF NOT EXISTS secret_question(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    question TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS app_user(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    username TEXT NOT NULL,
    secret_question_id INT NOT NULL,
    secret_question_answer TEXT NOT NULL,
    password_hash TEXT,
    expired_password BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_secret_question FOREIGN KEY(secret_question_id) REFERENCES secret_question(id)
);
CREATE TABLE IF NOT EXISTS album(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    app_user_id INT NOT NULL,
    CONSTRAINT fk_app_user FOREIGN KEY(app_user_id) REFERENCES app_user(id)
);
CREATE TABLE IF NOT EXISTS photo(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    file_type TEXT NOT NULL
);
